apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app.kubernetes.io/app: django-app
    app.kubernetes.io/name: django-deploy
    app.kubernetes.io/env: dev
    app.kubernetes.io/owner: SergeyPavlov
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      name: django
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: spawlov/django-app:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: django-config
          ports:
            - containerPort: 80
              name: http
      