apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  labels:
    app.kubernetes.io/name: django-config
    app.kubernetes.io/env: dev
    app.kubernetes.io/owner: SergeyPavlov
data:
  SECRET_KEY: "<FIX_ME: secret_key_for_django>"
  ALLOWED_HOSTS: "xx.xx.xx.xx,star-burger.test"
  DATABASE_URL: "FIX_ME: postgres://user:password@host:port/db_name"
  DEBUG: "False"

