apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
  labels:
    app.kubernetes.io/name: django-migrate
    app.kubernetes.io/env: dev
    app.kubernetes.io/owner: SergeyPavlov
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
        - name: django-app
          image: spawlov/django-app:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: django-config
          command:
            - python
            - manage.py
            - migrate
            - --noinput
      restartPolicy: Never