apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: edu-goofy-allen
  labels:
    app.kubernetes.io/app: nginx-service
spec:
  selector:
    app: nginx-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30351
  type: NodePort

